Repository sozu-proxy/sozu, pull requests merged in 2022-12, with the labels that each got.

#847 Enhance ScmSocket::set_blocking
  command/src/scm_socket.rs
  lib/src/server.rs
Labels: enhancement

#845 add brotli to encoding header values
  lib/src/protocol/http/parser/mod.rs
Labels: enhancement, h1

#848 prevent concurrent testing in the github CI
  .github/workflows/ci.yml
Labels: ci

#849 update build scripts with the `--locked` flag
  .travis.yml
  Dockerfile
  RELEASE.md
  doc/getting_started.md
  doc/how_to_use.md
  os-build/archlinux/PKGBUILD
  os-build/linux-rpm/README.md
  os-build/linux-rpm/sozu.spec
Labels: enhancement

#854 Fix Sessions close
  lib/src/http.rs
  lib/src/https.rs
  lib/src/tcp.rs
Labels: bug

#855 Propagate connect_to_backend errors with context
  lib/src/backends.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/server.rs
  lib/src/tcp.rs
Labels: enhancement

#859 merge client loop creation logic in the accept_clients function
  bin/src/command/mod.rs
Labels: enhancement

#862 import sozu-acme into the sozu command line
  Cargo.lock
  bin/Cargo.toml
  bin/src/acme.rs
  bin/src/cli.rs
  bin/src/ctl/mod.rs
  bin/src/main.rs
  bin/src/upgrade.rs
  bin/src/util.rs
Labels: enhancement, configuration, integration

#861 Abstract out notify functions
  lib/src/http.rs
  lib/src/https.rs
Labels: enhancement

#860 error propagation on HTTP and HTTPS frontend add and remove
  lib/src/http.rs
  lib/src/https.rs
  lib/src/router/mod.rs
Labels: enhancement

#863 Docker build and push to Docker Hub in the CI
  .github/workflows/ci.yml
  os-build/docker/config.toml
Labels: package, ci

#866 add documenting comments
  bin/src/command/mod.rs
  bin/src/command/orders.rs
  bin/src/command/worker.rs
  bin/src/upgrade.rs
  command/src/command.rs
  command/src/config.rs
  command/src/proxy.rs
  command/src/state.rs
  lib/src/server.rs
Labels: documentation

#867 comments on worker and upgrade logic
  bin/src/command/mod.rs
  bin/src/main.rs
  bin/src/upgrade.rs
  bin/src/worker.rs
  command/src/logging.rs
Labels: documentation
