Repository sozu-proxy/sozu, pull requests merged in 2022-10, with the labels that each got.

#812 Addresses part of #808 and #810
  command/src/state.rs
  lib/src/http.rs
  lib/src/https_openssl.rs
  lib/src/https_rustls/configuration.rs
  lib/src/https_rustls/session.rs
  lib/src/protocol/http/mod.rs
  lib/src/server.rs
  lib/src/tcp.rs
Labels: bug

#811 Lifetime of a session doc
  doc/lexicon.md
  doc/lifetime_of_a_session.md
  lib/src/http.rs
  lib/src/https_openssl.rs
  lib/src/https_rustls/session.rs
Labels: documentation

#818 Channel refactoring and testing
  Cargo.lock
  bin/Cargo.toml
  bin/src/command/orders.rs
  bin/src/ctl/mod.rs
  bin/src/upgrade.rs
  bin/src/worker.rs
  command/src/buffer/growable.rs
  command/src/channel.rs
  lib/Cargo.toml
  lib/src/server.rs
  lib/src/tcp.rs
Labels: enhancement

#821 Make the CLI accept processing messages
  bin/config.toml
  bin/src/command/mod.rs
  bin/src/command/orders.rs
  bin/src/ctl/command.rs
  bin/src/ctl/mod.rs
Labels: enhancement
