Repository sozu-proxy/sozu, pull requests merged in 2023-06, with the labels that each got.

#948 Better management of defaults in config
  bin/src/ctl/request_builder.rs
  command/src/config.rs
  command/src/lib.rs
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  e2e/src/tests/tests.rs
  lib/examples/main.rs
  lib/examples/minimal.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
Labels: configuration

#904 First integration of kawa in H1 state
  Cargo.lock
  bin/src/ctl/display.rs
  bin/src/main.rs
  bin/src/upgrade.rs
  bin/src/worker.rs
  command/src/channel.rs
  command/src/config.rs
  command/src/logging.rs
  command/src/ready.rs
  e2e/src/mock/async_backend.rs
  e2e/src/mock/client.rs
  e2e/src/mock/sync_backend.rs
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  e2e/src/tests/tests.rs
  lib/Cargo.toml
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/load_balancing.rs
  lib/src/logs.rs
  lib/src/metrics/mod.rs
  lib/src/metrics/writer.rs
  lib/src/pool.rs
  lib/src/protocol/h2/mod.rs
  lib/src/protocol/h2/state.rs
  lib/src/protocol/http/cookies.rs
  lib/src/protocol/http/mod.rs
  lib/src/protocol/http/parser/mod.rs
  lib/src/protocol/http/parser/request.rs
  lib/src/protocol/http/parser/response.rs
  lib/src/protocol/http/parser/tests.rs
  lib/src/protocol/kawa_h1/answers.rs
  lib/src/protocol/kawa_h1/editor.rs
  lib/src/protocol/kawa_h1/mod.rs
  lib/src/protocol/kawa_h1/parser.rs
  lib/src/protocol/mod.rs
  lib/src/protocol/pipe.rs
  lib/src/protocol/proxy_protocol/expect.rs
  lib/src/protocol/proxy_protocol/relay.rs
  lib/src/protocol/proxy_protocol/send.rs
  lib/src/protocol/rustls.rs
  lib/src/server.rs
  lib/src/socket.rs
  lib/src/tcp.rs
Labels: h1

#951 Access log counter, metrics
  lib/src/logs.rs
  lib/src/metrics/local_drain.rs
  lib/src/metrics/mod.rs
  lib/src/metrics/network_drain.rs
Labels: metrics, logs

#957 chore: update dependencies
  Cargo.lock
  bin/Cargo.toml
  command/Cargo.toml
  e2e/Cargo.toml
  lib/Cargo.toml
Labels: bug
