Repository sozu-proxy/sozu, pull requests merged in 2023-03, with the labels that each got.

#894 Update return for get_executable_path (freebsd)
  bin/src/worker.rs
Labels: package

#895 Command lib: simplify Request
  bin/src/acme.rs
  bin/src/cli.rs
  bin/src/command/mod.rs
  bin/src/command/requests.rs
  bin/src/command/worker.rs
  bin/src/ctl/command.rs
  bin/src/ctl/display.rs
  bin/src/ctl/mod.rs
  bin/src/ctl/request_builder.rs
  bin/src/main.rs
  bin/src/upgrade.rs
  bin/src/worker.rs
  command/assets/add_backend.json
  command/assets/add_certificate.json
  command/assets/add_cluster.json
  command/assets/add_http_front.json
  command/assets/add_https_front.json
  command/assets/dump_state.json
  command/assets/hard_stop.json
  command/assets/list_workers.json
  command/assets/load_state.json
  command/assets/remove_backend.json
  command/assets/remove_certificate.json
  command/assets/remove_cluster.json
  command/assets/remove_http_front.json
  command/assets/remove_https_front.json
  command/assets/save_state.json
  command/assets/soft_stop.json
  command/assets/status.json
  command/assets/upgrade_main.json
  command/assets/upgrade_worker.json
  command/src/certificate.rs
  command/src/command.rs
  command/src/config.rs
  command/src/lib.rs
  command/src/parser.rs
  command/src/proxy.rs
  command/src/request.rs
  command/src/response.rs
  command/src/state.rs
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  e2e/src/tests/tests.rs
  lib/examples/main.rs
  lib/examples/minimal.rs
  lib/examples/tcp.rs
  lib/src/backends.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/load_balancing.rs
  lib/src/metrics/local_drain.rs
  lib/src/metrics/mod.rs
  lib/src/protocol/http/mod.rs
  lib/src/protocol/pipe.rs
  lib/src/router/mod.rs
  lib/src/server.rs
  lib/src/tcp.rs
  lib/src/tls.rs
Labels: enhancement

#898 Refactor config
  bin/src/acme.rs
  bin/src/command/mod.rs
  bin/src/command/requests.rs
  bin/src/ctl/mod.rs
  bin/src/ctl/request_builder.rs
  command/assets/503.html
  command/src/config.rs
  command/src/request.rs
  command/src/response.rs
  command/src/state.rs
  e2e/src/http_utils/mod.rs
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  e2e/src/tests/tests.rs
  lib/examples/main.rs
  lib/examples/minimal.rs
  lib/examples/tcp.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/protocol/http/parser/tests.rs
  lib/src/server.rs
  lib/src/tcp.rs
  lib/src/tls.rs
Labels: enhancement, protobuf
