Repository sozu-proxy/sozu, pull requests merged in 2023-05, with the labels that each got.

#922 remove JSON serialization tests
  Dockerfile
  command/assets/add_backend.json
  command/assets/add_certificate.json
  command/assets/add_cluster.json
  command/assets/add_http_front.json
  command/assets/answer_metrics.json
  command/assets/answer_workers_status.json
  command/assets/dump_state.json
  command/assets/hard_stop.json
  command/assets/list_workers.json
  command/assets/load_state.json
  command/assets/protocol_mismatch.json
  command/assets/remove_backend.json
  command/assets/remove_certificate.json
  command/assets/remove_cluster.json
  command/assets/remove_http_front.json
  command/assets/remove_https_front.json
  command/assets/save_state.json
  command/assets/soft_stop.json
  command/assets/status.json
  command/assets/upgrade_main.json
  command/assets/upgrade_worker.json
  command/src/request.rs
  command/src/response.rs
  doc/architecture.md
  doc/how_to_use.md
Labels: protobuf

#918 Better check on session limits
  lib/src/lib.rs
  lib/src/server.rs
  lib/src/tcp.rs
Labels: enhancement

#928 Cosmetic todos
  bin/src/command/mod.rs
  bin/src/command/requests.rs
  bin/src/ctl/command.rs
  command/src/config.rs
  command/src/proto/mod.rs
  command/src/response.rs
  command/src/state.rs
  lib/src/https.rs
  lib/src/metrics/local_drain.rs
  lib/src/server.rs
Labels: enhancement

#930 apply clippy fixes
  bin/Cargo.toml
  bin/rust-toolchain
  bin/src/command/requests.rs
  bin/src/ctl/command.rs
  bin/src/ctl/display.rs
  bin/src/ctl/request_builder.rs
  command/Cargo.toml
  command/build.rs
  command/rust-toolchain
  command/src/config.rs
  command/src/proto/mod.rs
  command/src/request.rs
  command/src/response.rs
  command/src/state.rs
  e2e/Cargo.toml
  e2e/rust-toolchain
  e2e/src/tests/tests.rs
  lib/Cargo.toml
  lib/rust-toolchain
  lib/src/http.rs
  lib/src/https.rs
  lib/src/metrics/local_drain.rs
  lib/src/protocol/http/mod.rs
  lib/src/protocol/http/parser/response.rs
  lib/src/protocol/pipe.rs
  lib/src/protocol/proxy_protocol/header.rs
  lib/src/server.rs
  lib/src/tcp.rs
  lib/src/tls.rs
Labels: enhancement

#932 basic crate documentation on sozu
  bin/src/main.rs
Labels: documentation

#931 Update lib documentation
  lib/examples/main.rs
  lib/examples/minimal.rs
  lib/examples/tcp.rs
  lib/src/http.rs
  lib/src/lib.rs
  lib/src/server.rs
Labels: documentation

#935 Better listing of clusters and certificates in the CLI
  Cargo.lock
  bin/Cargo.toml
  bin/src/cli.rs
  bin/src/command/mod.rs
  bin/src/command/requests.rs
  bin/src/ctl/command.rs
  bin/src/ctl/display.rs
  bin/src/ctl/mod.rs
  bin/src/ctl/request_builder.rs
  bin/src/worker.rs
  command/src/command.proto
  command/src/config.rs
  command/src/lib.rs
  command/src/parser.rs
  command/src/proto/display.rs
  command/src/proto/mod.rs
  command/src/request.rs
  command/src/state.rs
  lib/examples/main.rs
  lib/examples/minimal.rs
  lib/examples/tcp.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/server.rs
  lib/src/tcp.rs
Labels: enhancement

#943 Create state directory and file if it does not exists
  bin/src/command/mod.rs
  bin/src/command/requests.rs
  bin/src/main.rs
  command/src/config.rs
Labels: enhancement
