Repository sozu-proxy/sozu, pull requests merged in 2024-02, with the labels that each got.

#1065 Socket address in protobuf
  bin/src/ctl/mod.rs
  bin/src/ctl/request_builder.rs
  bin/src/util.rs
  command/src/command.proto
  command/src/config.rs
  command/src/proto/display.rs
  command/src/request.rs
  command/src/response.rs
  command/src/state.rs
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  e2e/src/tests/tests.rs
  lib/examples/http.rs
  lib/examples/https.rs
  lib/examples/tcp.rs
  lib/src/backends.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/protocol/kawa_h1/mod.rs
  lib/src/server.rs
  lib/src/socket.rs
  lib/src/tcp.rs
  lib/src/tls.rs
Labels: protobuf

#1071 CI: Adding a benchmark framework
  .github/workflows/bench.py
  .github/workflows/bench.toml
  .github/workflows/benchmark.yml
  .github/workflows/ecdsa.cnf
  .github/workflows/rsa-2048.cnf
  .github/workflows/rsa-4096.cnf
Labels: enhancement, performance

#1000 Transmit config to new worker with a protobuf type + protobuf channels
  Cargo.lock
  bin/Cargo.toml
  bin/src/cli.rs
  bin/src/command/requests.rs
  bin/src/command/server.rs
  bin/src/command/sessions.rs
  bin/src/command/upgrade.rs
  bin/src/upgrade.rs
  bin/src/worker.rs
  command/src/channel.rs
  command/src/command.proto
  command/src/config.rs
  command/src/parser.rs
  command/src/request.rs
  command/src/response.rs
  command/src/scm_socket.rs
  command/src/state.rs
  command/state.json
  e2e/src/sozu/worker.rs
  e2e/src/tests/mod.rs
  lib/examples/http.rs
  lib/examples/https.rs
  lib/examples/tcp.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/metrics/local_drain.rs
  lib/src/server.rs
  lib/src/tcp.rs
Labels: protobuf

#1074 Fix certificate insertion
  command/src/certificate.rs
  command/src/command.proto
  command/src/state.rs
  lib/src/http.rs
  lib/src/https.rs
  lib/src/lib.rs
  lib/src/server.rs
  lib/src/tls.rs
Labels: bug, tls
